version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - htmlzip
  - pdf
  - epub

python:
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"