version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - pdf
  - epub

python:
  version: "3.12"
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    pip: "latest"
  commands:
    - make html